DataRFrames A DataFrame is a table-like structure consisting of rows and columns

In [1]:
import numpy as np
import pandas as pd

#DATA FRAME USING DICTANIORY

In [2]:
data = {
    'Name': ['John', 'Anna','Peter','Linda'],
    'Age':[28, 34, 29, 42],
    'City':['New York','Paris','Berlin','London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#DATA FRAME USING DATA LIST

In [3]:
data_list = [
    ['John', 28,'New York',65000],
    ['Anna', 34, 'Paris' , 42000],
    ['peter',29,'Berlin',72000],
    ['Linda', 42,'London', 85000]
]
pd.DataFrame(data_list)
columns = ["Name","Age", "City", "Price"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Price
0   John   28  New York  65000
1   Anna   34     Paris  42000
2  peter   29    Berlin  72000
3  Linda   42    London  85000

#NAME AND SELECTION OF COLUMN AND INSERTION OF DATA

In [4]:
df2[["Name", "City", "Price"]]

df2["designation"] = ["Doctor","Engg","CA", "UI/UX designer"]
df2

    Name  Age      City  Price     designation
0   John   28  New York  65000          Doctor
1   Anna   34     Paris  42000            Engg
2  peter   29    Berlin  72000              CA
3  Linda   42    London  85000  UI/UX designer

In [6]:
df2[['City','Price']]

       City  Price
0  New York  65000
1     Paris  42000
2    Berlin  72000
3    London  85000

#removing the column

In [13]:
df2.drop('designation', axis = 1, inplace=True)

In [14]:
df2

    Name  Age      City  Price
0   John   28  New York  65000
1   Anna   34     Paris  42000
2  peter   29    Berlin  72000
3  Linda   42    London  85000

In [12]:
df2.drop(["City", "Price"], axis =1)
df2

    Name  Age      City  Price     designation
0   John   28  New York  65000          Doctor
1   Anna   34     Paris  42000            Engg
2  peter   29    Berlin  72000              CA
3  Linda   42    London  85000  UI/UX designer

Selectiong rows

In [17]:
df2.loc[[0,1]]
df2.iloc[3]
df2

    Name  Age      City  Price
0   John   28  New York  65000
1   Anna   34     Paris  42000
2  peter   29    Berlin  72000
3  Linda   42    London  85000

selecting subset of rows and colums

In [19]:
df2.loc[[0,1]][["City", "Price"]]
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  peter   29
3  Linda   42

conditional selection

In [20]:
df2[df2["Age"] > 30]

    Name  Age    City  Price
1   Anna   34   Paris  42000
3  Linda   42  London  85000

In [21]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Price
1  Anna   34  Paris  42000